ui: tape
concurrency: 1
browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest-2
  - name: iphone
    version: latest
  - name: ie
    version: latest-2
  - name: opera
    platform: linux
    version: latest
  - name: safari
    version: latest