ui: tape
concurrency: 1
browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: 27..latest
  - name: iphone
    version: latest
  - name: ie
    version: 9..latest
  - name: opera
    version: latest